# Generated by Django 4.1.5 on 2023-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_rename_link_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Página",
                "verbose_name_plural": "Páginas",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="Orden"),
        ),
    ]
